# Generated by Django 3.2.12 on 2023-05-13 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
