# Generated by Django 3.2.12 on 2023-05-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_picture_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='icon',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='picture',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
